all_schools = [
"Adelphi University",
"American University",
"Amherst College",
"Appalachian State University",
"Arizona State University Campus Immersion",
"Auburn University",
"Ball State University",
"Barnard College",
"Barry University",
"Baylor University",
"Binghamton University",
"Boise State University",
"Boston College",
"Boston University",
"Bowling Green State University-Main Campus",
"Bradley University",
"Brigham Young University",
"Brown University",
"Bucknell University",
"Butler University",
"California Institute of Technology",
"California Polytechnic State University-San Luis Obispo",
"California State Polytechnic University-Pomona",
"California State University-Bakersfield",
"California State University-Chico",
"California State University-Dominguez Hills",
"California State University-East Bay",
"California State University-Fresno",
"California State University-Fullerton",
"California State University-Long Beach",
"California State University-Los Angeles",
"California State University-Monterey Bay",
"California State University-Northridge",
"California State University-Sacramento",
"California State University-San Bernardino",
"California State University-San Marcos",
"Carnegie Mellon University",
"Case Western Reserve University",
"Central Michigan University",
"Central Washington University",
"Chapman University",
"Clark Atlanta University",
"Clemson University",
"Cleveland State University",
"Coastal Carolina University",
"Colby College",
"Colgate University",
"College of Charleston",
"Colorado College",
"Colorado School of Mines",
"Colorado State University-Fort Collins",
"Columbia University in the City of New York",
"Cornell University",
"CUNY Bernard M Baruch College",
"CUNY City College",
"CUNY Hunter College",
"CUNY Queens College",
"Dartmouth College",
"DePaul University",
"Drexel University",
"Duke University",
"Duquesne University",
"East Carolina University",
"Eastern Michigan University",
"Elon University",
"Emerson College",
"Emory University",
"Fairfield University",
"Ferris State University",
"Florida Atlantic University",
"Florida Gulf Coast University",
"Florida Institute of Technology",
"Florida International University",
"Florida Southern College",
"Florida State University",
"Fordham University",
"George Mason University",
"George Washington University",
"Georgetown University",
"Georgia Institute of Technology-Main Campus",
"Georgia Southern University",
"Georgia State University",
"Grand Canyon University",
"Grand Valley State University",
"Grinnell College",
"Hampton University",
"Harvard University",
"Hawaii Pacific University",
"High Point University",
"Hofstra University",
"Howard University",
"Illinois State University",
"Indiana State University",
"Indiana University-Bloomington",
"Indiana University-Purdue University-Indianapolis",
"Iowa State University",
"Ithaca College",
"Jacksonville State University",
"James Madison University",
"Johns Hopkins University",
"Kennesaw State University",
"Kent State University at Kent",
"Lehigh University",
"Liberty University",
"Long Island University",
"Louisiana State University and Agricultural & Mechanical College",
"Loyola Marymount University",
"Loyola University Chicago",
"Manhattan College",
"Marist College",
"Marquette University",
"Massachusetts Institute of Technology",
"Merrimack College",
"Miami University-Oxford",
"Michigan State University",
"Middle Tennessee State University",
"Middlebury College",
"Mississippi State University",
"Montana State University",
"Montclair State University",
"Morgan State University",
"New Jersey Institute of Technology",
"New Mexico State University-Main Campus",
"New York Institute of Technology",
"New York University",
"North Carolina A & T State University",
"North Carolina State University at Raleigh",
"Northeastern University",
"Northern Arizona University",
"Northern Illinois University",
"Northwestern University",
"Nova Southeastern University",
"Oakland University",
"Oberlin College",
"Ohio State University-Main Campus",
"Ohio University-Main Campus",
"Oklahoma State University-Main Campus",
"Old Dominion University",
"Oregon State University",
"Pace University",
"Pennsylvania State University-Main Campus",
"Pepperdine University",
"Pomona College",
"Princeton University",
"Providence College",
"Purdue University-Main Campus",
"Quinnipiac University",
"Radford University",
"Rensselaer Polytechnic Institute",
"Rice University",
"Rochester Institute of Technology",
"Rowan University",
"Rutgers University-Camden",
"Rutgers University-New Brunswick",
"Rutgers University-Newark",
"Sacred Heart University",
"Saint Leo University",
"Saint Louis University",
"Sam Houston State University",
"San Diego State University",
"San Francisco State University",
"San Jose State University",
"Santa Clara University",
"Savannah College of Art and Design",
"Seton Hall University",
"Skidmore College",
"Sonoma State University",
"Southern Methodist University",
"Southern New Hampshire University",
"Southern Utah University",
"Spelman College",
"St. John's University-New York",
"Stanford University",
"State University of New York at New Paltz",
"State University of New York at Oswego",
"Stevens Institute of Technology",
"Stony Brook University",
"SUNY at Albany",
"SUNY Buffalo State University",
"SUNY Cortland",
"Swarthmore College",
"Syracuse University",
"Tarleton State University",
"Temple University",
"Texas A & M University-College Station",
"Texas A&M University-San Antonio",
"Texas Christian University",
"Texas Southern University",
"Texas State University",
"Texas Tech University",
"The College of New Jersey",
"The University of Alabama",
"The University of Tampa",
"The University of Tennessee-Knoxville",
"The University of Texas at Arlington",
"The University of Texas at Austin",
"The University of Texas at Dallas",
"The University of Texas at El Paso",
"The University of Texas at San Antonio",
"The University of Texas Rio Grande Valley",
"Towson University",
"Tufts University",
"Tulane University of Louisiana",
"University at Buffalo",
"University of Akron Main Campus",
"University of Alabama at Birmingham",
"University of Arizona",
"University of Arkansas",
"University of California-Berkeley",
"University of California-Davis",
"University of California-Irvine",
"University of California-Los Angeles",
"University of California-Merced",
"University of California-Riverside",
"University of California-San Diego",
"University of California-Santa Barbara",
"University of California-Santa Cruz",
"University of Central Florida",
"University of Chicago",
"University of Cincinnati-Main Campus",
"University of Colorado Boulder",
"University of Colorado Colorado Springs",
"University of Colorado Denver/Anschutz Medical Campus",
"University of Connecticut",
"University of Dayton",
"University of Delaware",
"University of Denver",
"University of Florida",
"University of Georgia",
"University of Hartford",
"University of Hawaii at Manoa",
"University of Houston",
"University of Illinois Chicago",
"University of Illinois Urbana-Champaign",
"University of Indianapolis",
"University of Iowa",
"University of Kansas",
"University of Kentucky",
"University of Louisiana at Lafayette",
"University of Louisville",
"University of Maine",
"University of Mary Hardin-Baylor",
"University of Maryland-Baltimore County",
"University of Maryland-College Park",
"University of Massachusetts-Amherst",
"University of Massachusetts-Boston",
"University of Massachusetts-Lowell",
"University of Memphis",
"University of Miami",
"University of Michigan-Ann Arbor",
"University of Minnesota-Twin Cities",
"University of Mississippi",
"University of Missouri-Columbia",
"University of Nebraska-Lincoln",
"University of Nevada-Las Vegas",
"University of New Hampshire-Main Campus",
"University of New Haven",
"University of New Mexico-Main Campus",
"University of North Carolina at Chapel Hill",
"University of North Carolina at Charlotte",
"University of North Carolina at Greensboro",
"University of North Carolina Wilmington",
"University of North Florida",
"University of North Georgia",
"University of North Texas",
"University of Northern Colorado",
"University of Notre Dame",
"University of Oklahoma-Norman Campus",
"University of Oregon",
"University of Pennsylvania",
"University of Pittsburgh-Pittsburgh Campus",
"University of Portland",
"University of Rhode Island",
"University of Richmond",
"University of Rochester",
"University of San Diego",
"University of San Francisco",
"University of South Alabama",
"University of South Carolina-Columbia",
"University of South Florida",
"University of Southern California",
"University of the Pacific",
"University of Utah",
"University of Vermont",
"University of Virginia-Main Campus",
"University of Washington-Seattle Campus",
"University of Wisconsin-Madison",
"University of Wisconsin-Milwaukee",
"Utah State University",
"Vanderbilt University",
"Vassar College",
"Villanova University",
"Virginia Commonwealth University",
"Virginia Polytechnic Institute and State University",
"Wake Forest University",
"Washington State University",
"Washington University in St Louis",
"Wayne State University",
"Wesleyan University",
"West Chester University of Pennsylvania",
"West Virginia University",
"Western Carolina University",
"Western Michigan University",
"Western Washington University",
"William & Mary",
"Williams College",
"Wingate University",
"Worcester Polytechnic Institute",
"Xavier University",
"Yale University"]

ans = [
"Stanford University",
"Harvard University",
"Massachusetts Institute of Technology",
"Columbia University in the City of New York",
"Princeton University",
"Yale University",
"Brown University",
"University of Pennsylvania",
"Duke University",
"Dartmouth College",
"University of Chicago",
"Northwestern University",
"Vanderbilt University",
"Johns Hopkins University",
"Cornell University",
"Rice University",
"Tulane University of Louisiana",
"University of California-Los Angeles",
"Tufts University",
"Georgetown University",
"University of Southern California",
"New York University",
"Washington University in St Louis",
"Emory University",
"Middlebury College",
"Carnegie Mellon University",
"University of California-Berkeley",
"University of Notre Dame",
"Georgia Institute of Technology-Main Campus",
"Colgate University",
"Northeastern University",
"Boston University",
"Boston College",
"Wesleyan University",
"University of Michigan-Ann Arbor",
"University of North Carolina at Chapel Hill",
"University of Virginia-Main Campus",
"Wake Forest University",
"Villanova University",
"University of Miami",
"The University of Texas at Austin",
"University of Richmond",
"University of California-Irvine",
"University of Florida",
"Case Western Reserve University",
"Skidmore College",
"University of California-San Diego",
"Bucknell University",
"Howard University",
"University of Central Florida",
"William & Mary",
"Florida State University",
"San Diego State University",
"University of Georgia",
"University of Rochester",
"Binghamton University",
"Emerson College",
"Loyola Marymount University",
"CUNY Hunter College",
"Lehigh University",
"State University of New York at New Paltz",
"California State University-Long Beach",
"North Carolina State University at Raleigh",
"Stony Brook University",
"Clemson University",
"University of South Florida",
"George Washington University",
"University of Maryland-College Park",
"Stevens Institute of Technology",
"University of San Diego",
"Pepperdine University",
"Rensselaer Polytechnic Institute",
"Southern Methodist University",
"University of Washington-Seattle Campus",
"The University of Tampa",
"Texas Christian University",
"Santa Clara University",
"University of Connecticut",
"Fairfield University",
"Virginia Polytechnic Institute and State University",
"Baylor University",
"Colorado School of Mines",
"Ohio State University-Main Campus",
"New Mexico State University-Main Campus",
"North Carolina A & T State University",
"Pennsylvania State University-Main Campus",
"Providence College",
"Clark Atlanta University",
"Fordham University",
"Brigham Young University",
"Syracuse University",
"California State University-Fullerton",
"University of Illinois Urbana-Champaign",
"Marist College",
"Worcester Polytechnic Institute",
"University of Wisconsin-Madison",
"Chapman University",
"SUNY Cortland",
"CUNY Queens College",
"University of South Carolina-Columbia",
"Wayne State University",
"University of Vermont",
"University of Denver",
"Florida International University",
"CUNY City College",
"American University",
"Texas A & M University-College Station",
"University of Houston",
"University of Massachusetts-Amherst",
"Sacred Heart University",
"University of Pittsburgh-Pittsburgh Campus",
"Hofstra University",
"Texas Tech University",
"SUNY at Albany",
"Rutgers University-New Brunswick",
"Ball State University",
"Oklahoma State University-Main Campus",
"Middle Tennessee State University",
"Purdue University-Main Campus",
"New Jersey Institute of Technology",
"DePaul University",
"University of Hawaii at Manoa",
"Texas State University",
"Saint Louis University",
"Northern Illinois University",
"University of South Alabama",
"Louisiana State University and Agricultural & Mechanical College",
"University of San Francisco",
"Auburn University",
"Rochester Institute of Technology",
"Temple University",
"University of Delaware",
"Montana State University",
"University of Minnesota-Twin Cities",
"University of Louisville",
"The University of Tennessee-Knoxville",
"College of Charleston",
"Mississippi State University",
"University of Rhode Island",
"University of Missouri-Columbia",
"Seton Hall University",
"Loyola University Chicago",
"Central Michigan University",
"University of North Florida",
"Elon University",
"Ithaca College",
"Northern Arizona University",
"University of Hartford",
"University of Illinois Chicago",
"California Institute of Technology",
"University of Colorado Boulder",
]


x = set(all_schools)
y = set(ans)
print(len(x))
print(len(y))
print(len(x & y))
print(len(x - y))
print(len(y - x))
print("="*20)

ind = []
for school in ans:
    ind.append(all_schools.index(school))

import random
random.shuffle(ind)
print(ind)