l = ["American University",
"Auburn University",
"Ball State University",
"Baylor University",
"Binghamton University",
"Boston College",
"Boston University",
"Brigham Young University",
"Brown University",
"Bucknell University",
"California Institute of Technology",
"California State University-Fullerton",
"California State University-Long Beach",
"Carnegie Mellon University",
"Case Western Reserve University",
"Central Michigan University",
"Chapman University",
"Clark Atlanta University",
"Clemson University",
"Colgate University",
"College of Charleston",
"Colorado School of Mines",
"Columbia University in the City of New York",
"Cornell University",
"CUNY City College",
"CUNY Hunter College",
"CUNY Queens College",
"Dartmouth College",
"DePaul University",
"Duke University",
"Elon University",
"Emerson College",
"Emory University",
"Fairfield University",
"Florida International University",
"Florida State University",
"Fordham University",
"George Washington University",
"Georgetown University",
"Georgia Institute of Technology-Main Campus",
"Harvard University",
"Hofstra University",
"Howard University",
"Ithaca College",
"Johns Hopkins University",
"Lehigh University",
"Louisiana State University and Agricultural & Mechanical College",
"Loyola Marymount University",
"Loyola University Chicago",
"Marist College",
"Massachusetts Institute of Technology",
"Middle Tennessee State University",
"Middlebury College",
"Mississippi State University",
"Montana State University",
"New Jersey Institute of Technology",
"New Mexico State University-Main Campus",
"New York University",
"North Carolina A & T State University",
"North Carolina State University at Raleigh",
"Northeastern University",
"Northern Arizona University",
"Northern Illinois University",
"Northwestern University",
"Ohio State University-Main Campus",
"Oklahoma State University-Main Campus",
"Pennsylvania State University-Main Campus",
"Pepperdine University",
"Princeton University",
"Providence College",
"Purdue University-Main Campus",
"Rensselaer Polytechnic Institute",
"Rice University",
"Rochester Institute of Technology",
"Rutgers University-New Brunswick",
"Sacred Heart University",
"Saint Louis University",
"San Diego State University",
"Santa Clara University",
"Seton Hall University",
"Skidmore College",
"Southern Methodist University",
"Stanford University",
"State University of New York at New Paltz",
"Stevens Institute of Technology",
"Stony Brook University",
"SUNY at Albany",
"SUNY Cortland",
"Syracuse University",
"Temple University",
"Texas A & M University-College Station",
"Texas Christian University",
"Texas State University",
"Texas Tech University",
"The University of Tampa",
"The University of Tennessee-Knoxville",
"The University of Texas at Austin",
"Tufts University",
"Tulane University of Louisiana",
"University of California-Berkeley",
"University of California-Irvine",
"University of California-Los Angeles",
"University of California-San Diego",
"University of Central Florida",
"University of Chicago",
"University of Colorado Boulder",
"University of Connecticut",
"University of Delaware",
"University of Denver",
"University of Florida",
"University of Georgia",
"University of Hartford",
"University of Hawaii at Manoa",
"University of Houston",
"University of Illinois Chicago",
"University of Illinois Urbana-Champaign",
"University of Louisville",
"University of Maryland-College Park",
"University of Massachusetts-Amherst",
"University of Miami",
"University of Michigan-Ann Arbor",
"University of Minnesota-Twin Cities",
"University of Missouri-Columbia",
"University of North Carolina at Chapel Hill",
"University of North Florida",
"University of Notre Dame",
"University of Pennsylvania",
"University of Pittsburgh-Pittsburgh Campus",
"University of Rhode Island",
"University of Richmond",
"University of Rochester",
"University of San Diego",
"University of San Francisco",
"University of South Alabama",
"University of South Carolina-Columbia",
"University of South Florida",
"University of Southern California",
"University of Vermont",
"University of Virginia-Main Campus",
"University of Washington-Seattle Campus",
"University of Wisconsin-Madison",
"Vanderbilt University",
"Villanova University",
"Virginia Polytechnic Institute and State University",
"Wake Forest University",
"Washington University in St Louis",
"Wayne State University",
"Wesleyan University",
"William & Mary",
"Worcester Polytechnic Institute",
"Yale University"]

import random
random.shuffle(l)
print('\n'.join(l))